# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_arguments.ipynb.

# %% auto 0
__all__ = ['parse_arg', 'parse_attrs']

# %% ../nbs/99_arguments.ipynb 2
import json

# %% ../nbs/99_arguments.ipynb 4
def parse_arg(arg):
    try:
        v = json.loads(arg)
    except json.JSONDecodeError:
        v = arg
    return v

# %% ../nbs/99_arguments.ipynb 7
def parse_attrs(attrs):
    for k, y in attrs.items():
        attrs[k] = parse_arg(y)
    return attrs
