# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/templates.ipynb.

# %% auto 0
__all__ = ['render']

# %% ../nbs/templates.ipynb 2
from typing import Any, Optional
from jinja2 import Environment, BaseLoader, Template, StrictUndefined

# %% ../nbs/templates.ipynb 4
def _get_env():
    return Environment(loader=BaseLoader(), undefined=StrictUndefined)

# %% ../nbs/templates.ipynb 6
def render(
    template: str,  # template in string form
    filters: Optional[dict] = None,  # jinja filters
    **kwargs: Any,
) -> str:
    if not filters:
        filters = {}

    env = _get_env()
    env.filters.update(filters)

    jinja: Template = env.from_string(template)
    result: str = jinja.render(**kwargs)

    return result
