# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_utils.ipynb.

# %% auto 0
__all__ = ['files']

# %% ../nbs/99_utils.ipynb 3
from contextlib import contextmanager
from pathlib import Path
from typing import Generator


@contextmanager
def files(content: dict[str, str]) -> Generator:
    """Setup files with content. No override if file already exists."""
    try:
        for filepath, text in content.items():
            path = Path(filepath)
            if path.exists():
                raise RuntimeError("This file already exists {path}")
            path.write_text(text)

        yield

    finally:
        for filepath in content.keys():
            path = Path(filepath)
            path.unlink()
