# pre-commit install
# https://nbdev.fast.ai/tutorials/pre_commit.html
# https://pre-commit.com/hooks.html
repos:
- repo: https://github.com/python-poetry/poetry
  rev: '1.7.0'  # add version here
  hooks:
    - id: poetry-check
    - id: poetry-lock
- repo: local
  hooks:
    - id: nbdev_clean
      name: nbdev_clean
      entry: nbdev_clean --clear_all
      description: "Clean metadata from notebooks to avoid merge conflicts"
      language: python
      always_run: true
      pass_filenames: false
    - id: nbdev_test
      name: nbdev_test
      entry: nbdev_test
      description: "Run tests in notebooks"
      language: python
      always_run: true
      pass_filenames: false
    - id: nbdev_export
      language: python
      always_run: true
      pass_filenames: false
      name: nbdev_export
      entry: nbdev_export --procs black_format scrub_magics
      description: "Export notebooks to modules and build modidx"
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
    - id: ruff
      name: ruff
      entry: ruff
      language: system
      types: [python]
      exclude: ^(sal\/_modidx\.py)$
    # - id: black
    #   name: black
    #   entry: black
    #   language: system
    #   types: [python] 